import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ShoppingBag, Search, Menu, X, Plus, Minus, Trash2, MessageCircle, Truck, User, LogOut, ArrowRight, Leaf, Package, Lock, Headphones, Flame, Sparkles, Instagram, Facebook, Youtube } from 'lucide-react'
import { products } from './products'
import { supabase } from './lib/supabase'
import './styles.css'

const waNumber = '919999999999'
const kitItems = ['Camphor — 250gm','Laal & Peela Kapda','Dhoop Batti','Chota Perfume / Itra','Roli — 1 packet','Laal Chunri — 1','Chandan Tika — 1','Pooja Ghee — 150gm','Cotton Batti — 1 packet']
const categoryIcons = { Cloth:'🧣','Pooja Essentials':'🪔','Eco-Friendly':'🌿',Incense:'🕯️',Fragrance:'🌸',Wicks:'🔥',Oil:'🪔',Hawan:'🔥',Sindoor:'🔴','Pooja Kits':'🎁',Mala:'📿',Asan:'🧘' }
const categoryImageFallbacks = { Cloth:'/products/01-peela-kapda.jpg','Pooja Essentials':'/products/03-pooja-ghee.jpg','Eco-Friendly':'/products/04-gobar-cups-diya.jpg',Incense:'/products/07-dhoop.jpg',Fragrance:'/products/08-perfumes-itra.jpg',Wicks:'/products/11-cotton-batti.jpg',Oil:'/products/13-chameli-pooja-oil.jpg',Hawan:'/products/17-hawan-samagri.jpg',Sindoor:'/products/18-orange-sindoor.jpg','Pooja Kits':'/products/20-nav-grah-poojan.jpg',Mala:'/products/28-rudraksh-mala.jpg',Asan:'/products/31-red-ooni-asan.jpg' }
function getCategoryImage(category){ return products.find(p=>p.category===category)?.image || categoryImageFallbacks[category] }

function App(){
 const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [cart,setCart]=useState([]); const [cartOpen,setCartOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false); const [authOpen,setAuthOpen]=useState(false); const [user,setUser]=useState(null)
 useEffect(()=>{let mounted=true; supabase.auth.getSession().then(({data})=>{if(mounted)setUser(data.session?.user||null)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null)); return()=>{mounted=false;subscription.unsubscribe()}},[])
 const categories=useMemo(()=>['All',...new Set(products.map(p=>p.category))],[])
 const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query])
 const add=p=>setCart(c=>{const f=c.find(x=>x.id===p.id);return f?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]})
 const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+d}:i).filter(i=>i.qty>0)); const remove=id=>setCart(c=>c.filter(i=>i.id!==id)); const cartCount=cart.reduce((t,i)=>t+i.qty,0)
 const logout=async()=>supabase.auth.signOut()
 const orderWhatsApp=(items=cart,title='Poojan Paradise Order')=>{if(!items.length)return;const lines=items.map(i=>`• ${i.name} × ${i.qty} — ₹${i.price} (${i.unit})`).join('\n');const total=items.reduce((s,i)=>s+i.price*i.qty,0);window.open(`https://wa.me/${waNumber}?text=${encodeURIComponent(`Namaste Poojan Paradise!\n\n${title}\n\n${lines}\n\nTotal: ₹${total}\n\nPlease share delivery details.`)}`,'_blank')}
 const scrollToShop=()=>document.getElementById('shop')?.scrollIntoView({behavior:'smooth'})
 const closeMenu=()=>setMenuOpen(false)
 return <div className="site">
  <header className="main-header"><div className="header-inner"><a href="#home" className="brand" onClick={closeMenu}><img src="/logo.png" alt="Poojan Paradise"/><div className="brand-text"><strong>POOJAN PARADISE</strong><small>Shuddh Samagri • Shreshth Seva</small></div></a><button className="mobile-menu-btn" aria-label="Open navigation menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={25}/>:<Menu size={25}/>}</button><nav className={menuOpen?'nav open':'nav'}><a href="#home" onClick={closeMenu}>Home</a><a href="#shop" onClick={closeMenu}>Shop</a><a href="#kit" onClick={closeMenu}>Poojan Kit</a><a href="#offers" onClick={closeMenu}>Offers</a><a href="#about" onClick={closeMenu}>About Us</a><a href="#contact" onClick={closeMenu}>Contact</a></nav><div className="header-icons"><button className="header-icon" onClick={scrollToShop} aria-label="Search products"><Search/></button>{user?<button className="header-icon" onClick={logout} aria-label="Logout"><LogOut/></button>:<button className="header-icon" onClick={()=>setAuthOpen(true)} aria-label="Account"><User/></button>}<button className="header-icon cart-icon" onClick={()=>setCartOpen(true)} aria-label="Shopping cart"><ShoppingBag/>{cartCount>0&&<b>{cartCount}</b>}</button></div></div></header>
  <section id="home" className="hero"><div className="hero-inner"><div className="hero-copy"><span className="gold-eyebrow"><Sparkles size={15}/> SHUDDH SAMAGRI • SHRESHTH SEVA</span><h1>Pure Devotion,<br/><em>Better Tomorrow</em></h1><p className="hero-subtitle">Your One Stop Shop For<br/>All Pooja Needs</p><div className="hero-features"><div><Leaf/><span><b>Authentic</b>Products</span></div><div><Package/><span><b>Trusted by</b> Families</span></div><div><Truck/><span><b>Pan India</b>Delivery</span></div></div><button className="gold-hero-btn" onClick={scrollToShop}>Shop Now <ArrowRight size={20}/></button></div><div className="hero-visual"><img src="/hero-pooja.png" alt="Poojan Paradise Pooja Setup" className="hero-main-image"/></div></div></section>
  <section className="category-section"><div className="ornament-title"><span>❧</span><h2>Shop By Category</h2><span>❧</span></div><div className="category-grid">{categories.filter(x=>x!=='All').slice(0,9).map(cat=><button className="category-card" key={cat} onClick={()=>{setCategory(cat);scrollToShop()}}><div className="category-circle">{getCategoryImage(cat)?<img src={getCategoryImage(cat)} alt={cat}/>:<span>{categoryIcons[cat]||'🪔'}</span>}</div><strong>{cat}</strong></button>)}</div></section>
  <section id="shop" className="shop-section"><div className="section-heading-row"><div className="ornament-title"><span>❧</span><h2>Shop Pooja Essentials</h2><span>❧</span></div></div><div className="shop-controls"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-image"><img src={p.image} alt={p.name}/></div><div className="product-info"><span>{p.category}</span><h3>{p.name}</h3><strong>₹{p.price}</strong><small>{p.unit}</small><button className="gold-btn" onClick={()=>add(p)}>Add to Cart</button></div></article>)}</div></section>
  <section id="kit" className="kit-section"><div className="ornament-title"><span>❧</span><h2>Premium Poojan Kit</h2><span>❧</span></div><div className="kit-card"><div><h2>Everything You Need for Your Pooja</h2><p>A thoughtfully curated collection of essential pooja samagri from Poojan Paradise.</p><ul>{kitItems.map(i=><li key={i}>{i}</li>)}</ul></div><div><strong className="kit-price">₹1,299</strong><button className="gold-btn" onClick={()=>orderWhatsApp([{id:'kit-1299',name:'Premium Poojan Kit',price:1299,unit:'1 kit',qty:1}],'Premium Poojan Kit')}>Order Kit</button></div></div></section>
  <section id="offers" className="coin-offer-section"><div className="ornament-title"><span>❧</span><h2>Special Poojan Paradise Offer</h2><span>❧</span></div><div className="coin-offer-card"><div className="coin-visual"><img src="/shagun coin.png" alt="Shagun Coin" className="shagun-coin"/><img src="/para coin.png" alt="Para Coin" className="para-coin"/></div><div className="coin-offer-content"><span className="gold-eyebrow">PRE-LAUNCH OFFER</span><h2>Shagun Coin & Para Coin</h2><p>Eligible participants can receive the Shagun Coin valued at ₹11,000 and the Para Coin valued at ₹10,000, subject to the applicable offer terms.</p><div className="offer-steps"><div><strong>01</strong><span>Purchase eligible Poojan Paradise kits.</span></div><div><strong>02</strong><span>Complete the required purchases within the offer period.</span></div><div><strong>03</strong><span>Meet the applicable eligibility criteria to unlock the relevant reward.</span></div></div><button className="gold-btn" onClick={scrollToShop}>Shop Now <ArrowRight size={18}/></button></div></div></section>
  <section className="why-section"><div className="ornament-title"><span>❧</span><h2>Why Choose Poojan Paradise?</h2><span>❧</span></div><div className="why-grid"><div className="why-item"><div><Leaf/></div><strong>Authentic</strong><span>Products</span></div><div className="why-item"><div><Flame/></div><strong>Inspired by</strong><span>Sanatan Values</span></div><div className="why-item"><div><Lock/></div><strong>Secure</strong><span>Payments</span></div><div className="why-item"><div><Truck/></div><strong>Fast & Safe</strong><span>Delivery</span></div><div className="why-item"><div><Headphones/></div><strong>Dedicated</strong><span>Customer Support</span></div></div></section>
  <section id="about" className="about-section"><div className="about-logo"><img src="/logo.png" alt="Poojan Paradise"/></div><div className="about-copy"><span className="gold-eyebrow">POOJAN PARADISE</span><h2>Purity in Devotion,<br/><em>Prosperity in Growth!</em></h2><p>Welcome to Poojan Paradise. Our mission is to make authentic, thoughtfully selected pooja essentials accessible to households across India.</p><h3>🌟 Founding Member Loyalty Program</h3><p>Eligible members can participate in our founding-member program and work toward rewards associated with the Shagun Coin and Para Coin, subject to the published terms and eligibility criteria.</p><div className="about-program"><div className="about-program-item"><strong>Shagun Coin — Value ₹11,000</strong><span>Available to eligible participants under the applicable offer terms.</span></div><div className="about-program-item"><strong>Para Coin — Value ₹10,000</strong><span>Available after meeting the applicable founding-member milestones and terms.</span></div></div><h3>💰 Combined Coin Value — ₹21,000</h3><p>The stated values are ₹11,000 for the Shagun Coin and ₹10,000 for the Para Coin. Rewards are subject to the official program terms, eligibility requirements and applicable conditions.</p><div className="about-note"><strong>Note:</strong> Program availability and limits are subject to the official terms and conditions.</div></div></section>
  <footer id="contact"><div>© Poojan Paradise • Shuddh Samagri • Shreshth Seva</div></footer>
  {authOpen&&<div className="modal-overlay" onClick={()=>setAuthOpen(false)}><div className="auth-card" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAuthOpen(false)}><X/></button><img src="/logo.png" className="auth-logo" alt="Poojan Paradise"/><h2>Welcome Back</h2><p>Login to your Poojan Paradise account</p><input type="email" placeholder="Email Address"/><input type="password" placeholder="Password"/><button className="gold-btn">Login</button></div></div>}
  {cartOpen&&<div className="modal-overlay" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="cart-header"><h2>Your Cart</h2><button onClick={()=>setCartOpen(false)}><X/></button></div>{cart.map(item=><div className="cart-item" key={item.id}><img src={item.image} alt={item.name}/><div><strong>{item.name}</strong><small>₹{item.price} • {item.unit}</small><div className="cart-qty"><button onClick={()=>change(item.id,-1)}><Minus/></button><b>{item.qty}</b><button onClick={()=>change(item.id,1)}><Plus/></button><button onClick={()=>remove(item.id)}><Trash2/></button></div></div></div>)}{cart.length>0&&<button className="whatsapp-btn" onClick={()=>orderWhatsApp()}> <MessageCircle/> Order Cart on WhatsApp</button>}</aside></div>}
 </div>
}

createRoot(document.getElementById('root')).render(<App />)
