export const products = [
  {
    id: 1,
    name: "Peela Kapda",
    category: "Cloth",
    price: 49,
    unit: "1.25m",
    image: "/products/01-peela-kapda.jpg",
  },
  {
    id: 2,
    name: "Lal Kapda",
    category: "Cloth",
    price: 49,
    unit: "1.25m",
    image: "/products/02-lal-kapda.jpg",
  },
  {
    id: 3,
    name: "Pooja Ghee",
    category: "Pooja Essentials",
    price: 180,
    unit: "200ml",
    image: "/products/03-pooja-ghee.jpg",
  },
  {
    id: 4,
    name: "Gobar Cups & Diya",
    category: "Eco-Friendly",
    price: 299,
    unit: "40 pcs",
    image: "/products/04-gobar-cups-diya.jpg",
  },
  {
    id: 5,
    name: "Kapoor (Bheem Seni)",
    category: "Pooja Essentials",
    price: 225,
    unit: "100g",
    image: "/products/05-kapoor-bheem-seni.jpg",
  },
  {
    id: 6,
    name: "Honey",
    category: "Pooja Essentials",
    price: 159,
    unit: "150g",
    image: "/products/06-honey.jpg",
  },
  {
    id: 7,
    name: "Dhoop Batti",
    category: "Incense",
    price: 69,
    unit: "30 pcs",
    image: "/products/07-dhoop.jpg",
  },
  {
    id: 8,
    name: "Perfumes / Itra",
    category: "Fragrance",
    price: 99,
    unit: "100ml",
    image: "/products/08-perfumes-itra.jpg",
  },
  {
    id: 9,
    name: "Kalava",
    category: "Pooja Essentials",
    price: 39,
    unit: "1 roll",
    image: "/products/09-kalava.jpg",
  },
  {
    id: 10,
    name: "Roli",
    category: "Pooja Essentials",
    price: 29,
    unit: "1 packet",
    image: "/products/10-roli.jpg",
  },
  {
    id: 11,
    name: "Cotton Batti",
    category: "Wicks",
    price: 49,
    unit: "1 packet",
    image: "/products/11-cotton-batti.jpg",
  },
  {
    id: 12,
    name: "Cow Ghee Batti",
    category: "Wicks",
    price: 99,
    unit: "1 packet",
    image: "/products/12-cow-ghee-batti.jpg",
  },
  {
    id: 13,
    name: "Chameli Pooja Oil",
    category: "Oil",
    price: 89,
    unit: "100ml",
    image: "/products/13-chameli-pooja-oil.jpg",
  },
  {
    id: 14,
    name: "Lal Chunri",
    category: "Cloth",
    price: 49,
    unit: "1 pc",
    image: "/products/14-lal-chunri.jpg",
  },
  {
    id: 15,
    name: "Peeli Chunri",
    category: "Cloth",
    price: 49,
    unit: "1 pc",
    image: "/products/15-peeli-chunri.jpg",
  },
  {
    id: 16,
    name: "Tika Chandan",
    category: "Pooja Essentials",
    price: 59,
    unit: "1 pack",
    image: "/products/16-tika-chandan.jpg",
  },
  {
    id: 17,
    name: "Hawan Samagri",
    category: "Hawan",
    price: 99,
    unit: "250g",
    image: "/products/17-hawan-samagri.jpg",
  },
  {
    id: 18,
    name: "Orange Sindoor",
    category: "Sindoor",
    price: 39,
    unit: "1 pack",
    image: "/products/18-orange-sindoor.jpg",
  },
  {
    id: 19,
    name: "Lal Sindoor",
    category: "Sindoor",
    price: 39,
    unit: "1 pack",
    image: "/products/19-lal-sindoor.jpg",
  },
  {
    id: 20,
    name: "Nav Grah Poojan",
    category: "Pooja Kits",
    price: 149,
    unit: "1 kit",
    image: "/products/20-nav-grah-poojan.jpg",
  },
  {
    id: 21,
    name: "Haldi Sabut",
    category: "Pooja Essentials",
    price: 49,
    unit: "100g",
    image: "/products/21-haldi-sabut.jpg",
  },
  {
    id: 22,
    name: "Peeli Kaudi",
    category: "Pooja Essentials",
    price: 79,
    unit: "11 pcs",
    image: "/products/22-peeli-kaudi.jpg",
  },
  {
    id: 23,
    name: "Gomti Chakra",
    category: "Pooja Essentials",
    price: 99,
    unit: "11 pcs",
    image: "/products/23-gomti-chakra.jpg",
  },
  {
    id: 24,
    name: "Janaeu",
    category: "Pooja Essentials",
    price: 39,
    unit: "1 pack",
    image: "/products/24-janaeu.jpg",
  },
  {
    id: 25,
    name: "Cow Dung Cake",
    category: "Eco-Friendly",
    price: 99,
    unit: "10 pcs",
    image: "/products/25-cow-dung-cake.jpg",
  },
  {
    id: 26,
    name: "Guggal",
    category: "Hawan",
    price: 99,
    unit: "100g",
    image: "/products/26-guggal.jpg",
  },
  {
    id: 27,
    name: "Loban",
    category: "Hawan",
    price: 79,
    unit: "100g",
    image: "/products/27-loban.jpg",
  },
  {
    id: 28,
    name: "Rudraksh Mala",
    category: "Mala",
    price: 199,
    unit: "1 mala",
    image: "/products/28-rudraksh-mala.jpg",
  },
  {
    id: 29,
    name: "Kamal Gatta Mala / Loose",
    category: "Mala",
    price: 149,
    unit: "1 mala",
    image: "/products/29-kamal-gatta-mala-loose.jpg",
  },
  {
    id: 30,
    name: "Chandan Sticks / Rubbing Stone",
    category: "Pooja Essentials",
    price: 129,
    unit: "1 set",
    image: "/products/30-chandan-sticks-rubbing-stone.jpg",
  },
  {
    id: 31,
    name: "Red Ooni Asan",
    category: "Asan",
    price: 299,
    unit: "1 pc",
    image: "/products/31-red-ooni-asan.jpg",
  },
  {
    id: 32,
    name: "Yellow Ooni Asan",
    category: "Asan",
    price: 299,
    unit: "1 pc",
    image: "/products/32-yellow-ooni-asan.jpg",
  },

  // Dhoop Batti 50 pcs variant
  {
    id: 33,
    name: "Dhoop Batti - 50 pcs",
    category: "Incense",
    price: 115,
    unit: "50 pcs",
    image: "/products/07-dhoop.jpg",
  },

  // Small Dhoop Batti
  {
    id: 34,
    name: "Dhoop Batti Small",
    category: "Incense",
    price: 63,
    unit: "30 pcs",
    image: "/products/07-dhoop.jpg",
  },
];